feat: add docker and tested all project endpoints

diff --git a/entry_point b/entry_point
--- a/entry_point
+++ b/entry_point
@@ -1,10 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 
-echo "Waiting for PostgreSQL..."
-until nc -z localhost 5432; do
-    sleep 1
-done
-echo "PostgreSQL is up!"
+set -e
 
-python manage.py migrate --noinput
-python manage.py runserver 0.0.0.0:8000
+echo "Initializing project..."
+
+echo "Checking for model changes..."
+python3 manage.py makemigrations
+
+# 2. Apply migrations
+echo "Applying database migrations..."
+if python3 manage.py migrate --noinput; then
+    echo "SUCCESS: Migrations applied."
+else
+    echo "ERROR: Failed to apply migrations. Exiting."
+    exit 1
+fi
+
+# 3. Start the server
+# Using exec ensures the Django process receives OS signals (like SIGTERM) directly
+echo "--> Starting development server on port 8000..."
+exec python3 manage.py runserver 0.0.0.0:8000
+
+
+
+
+
